### ISSUE TITLE
gather_config error

### ISSUE THREAD

**Issue by drshawnthesheep** [microsoft/msrc-appconfig#7]
`app_config = gather_config(AppConfig)` lead to an error `Unknown arguments: ...` & `NameError: name 'exit' is not defined` when running in interactive python.

Thanks :)

**Comment by vassilyl** [comment]
This happens, e.g., in Jupyter which passes arguments to a kernel. To disable interpretation of `sys.argv` in such a case add `argv=[]` argument to `gather_config`.
